"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.


"""
from collections import  Counter
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_map = Counter(s)
        t_map = Counter(t)
        for key, value in t_map.items():
            if key not in s_map.keys():
                return key
            elif key in s_map.keys() and value != s_map[key]:
                return key
            else:
                continue


if __name__ == '__main__':
    s = "abcd"
    t = "abcde"
    sol = Solution()
    result = sol.findTheDifference(s, t)
    print(result)